//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStatReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://rs/asoft/nlgs/webservices/transactionservice", ConfigurationName="GameStatReference.SaveTransactionService")]
    public interface SaveTransactionService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GameStatReference.TransactionResponse1> TransactionAsync(GameStatReference.TransactionRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rs/asoft/nlgs/webservices/transactionservice")]
    public partial class TransactionRequest
    {
        
        private string ticketReferenceField;
        
        private int permitHolderIdField;
        
        private int gameTypeField;
        
        private string drawingDateTimeField;
        
        private int sourceField;
        
        private int transactionTypeField;
        
        private string providerIdentifierField;
        
        private string transactionTimestampField;
        
        private decimal transactionAmountField;
        
        private string sourceIdentifierField;
        
        private string transactionDescField;
        
        private string winingDrawDateTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ticketReference
        {
            get
            {
                return this.ticketReferenceField;
            }
            set
            {
                this.ticketReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int permitHolderId
        {
            get
            {
                return this.permitHolderIdField;
            }
            set
            {
                this.permitHolderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int gameType
        {
            get
            {
                return this.gameTypeField;
            }
            set
            {
                this.gameTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string drawingDateTime
        {
            get
            {
                return this.drawingDateTimeField;
            }
            set
            {
                this.drawingDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int transactionType
        {
            get
            {
                return this.transactionTypeField;
            }
            set
            {
                this.transactionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string providerIdentifier
        {
            get
            {
                return this.providerIdentifierField;
            }
            set
            {
                this.providerIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string transactionTimestamp
        {
            get
            {
                return this.transactionTimestampField;
            }
            set
            {
                this.transactionTimestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal transactionAmount
        {
            get
            {
                return this.transactionAmountField;
            }
            set
            {
                this.transactionAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string sourceIdentifier
        {
            get
            {
                return this.sourceIdentifierField;
            }
            set
            {
                this.sourceIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string transactionDesc
        {
            get
            {
                return this.transactionDescField;
            }
            set
            {
                this.transactionDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string winingDrawDateTime
        {
            get
            {
                return this.winingDrawDateTimeField;
            }
            set
            {
                this.winingDrawDateTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rs/asoft/nlgs/webservices/transactionservice")]
    public partial class TransactionResponse
    {
        
        private string responseField;
        
        private string dateRequestField;
        
        private string dateResponseField;
        
        private string transactionNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string dateRequest
        {
            get
            {
                return this.dateRequestField;
            }
            set
            {
                this.dateRequestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string dateResponse
        {
            get
            {
                return this.dateResponseField;
            }
            set
            {
                this.dateResponseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string transactionNumber
        {
            get
            {
                return this.transactionNumberField;
            }
            set
            {
                this.transactionNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransactionRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rs/asoft/nlgs/webservices/transactionservice", Order=0)]
        public GameStatReference.TransactionRequest TransactionRequest;
        
        public TransactionRequest1()
        {
        }
        
        public TransactionRequest1(GameStatReference.TransactionRequest TransactionRequest)
        {
            this.TransactionRequest = TransactionRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransactionResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rs/asoft/nlgs/webservices/transactionservice", Order=0)]
        public GameStatReference.TransactionResponse TransactionResponse;
        
        public TransactionResponse1()
        {
        }
        
        public TransactionResponse1(GameStatReference.TransactionResponse TransactionResponse)
        {
            this.TransactionResponse = TransactionResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface SaveTransactionServiceChannel : GameStatReference.SaveTransactionService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class SaveTransactionServiceClient : System.ServiceModel.ClientBase<GameStatReference.SaveTransactionService>, GameStatReference.SaveTransactionService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SaveTransactionServiceClient() : 
                base(SaveTransactionServiceClient.GetDefaultBinding(), SaveTransactionServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.SaveTransactionServiceSoap11.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SaveTransactionServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SaveTransactionServiceClient.GetBindingForEndpoint(endpointConfiguration), SaveTransactionServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SaveTransactionServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SaveTransactionServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SaveTransactionServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SaveTransactionServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SaveTransactionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GameStatReference.TransactionResponse1> GameStatReference.SaveTransactionService.TransactionAsync(GameStatReference.TransactionRequest1 request)
        {
            return base.Channel.TransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<GameStatReference.TransactionResponse1> TransactionAsync(GameStatReference.TransactionRequest TransactionRequest)
        {
            GameStatReference.TransactionRequest1 inValue = new GameStatReference.TransactionRequest1();
            inValue.TransactionRequest = TransactionRequest;
            return ((GameStatReference.SaveTransactionService)(this)).TransactionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SaveTransactionServiceSoap11))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SaveTransactionServiceSoap11))
            {
                return new System.ServiceModel.EndpointAddress("http://178.253.196.22:9080/AsoftNLGS/endpoints");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SaveTransactionServiceClient.GetBindingForEndpoint(EndpointConfiguration.SaveTransactionServiceSoap11);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SaveTransactionServiceClient.GetEndpointAddress(EndpointConfiguration.SaveTransactionServiceSoap11);
        }
        
        public enum EndpointConfiguration
        {
            
            SaveTransactionServiceSoap11,
        }
    }
}
